service: tracks-service

provider:
  name: aws
  runtime: nodejs12.x # set node.js runtime
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  stage: dev # setting the env stage to dev, this will be visible in the routes
  region: us-east-1

functions: # add 4 functions for CRUD
  create:
    handler: handler.create # point to exported create function in handler.js
    events:
      - http:
          path: tracks # path will be domain.name.com/dev/tracks
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: tracks/{id} # path will be domain.name.com/dev/tracks/1
          method: get
          cors: true
  getAll:
    handler: handler.getAll # path will be domain.name.com/dev/tracks
    events:
      - http:
          path: tracks
          method: get
          cors: true
  update:
    handler: handler.update # path will be domain.name.com/dev/tracks/1
    events:
      - http:
          path: tracks/{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: tracks/{id} # path will be domain.name.com/dev/tracks/1
          method: delete
          cors: true

plugins:
  - serverless-offline # adding the plugin to be able to run the offline emulation
